<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rtsc" nsURI="http://org.muml.xsrtsc.xsrtsc/rtsc/" nsPrefix="rtsc">
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviouralElement" eType="//BehavioralElement" containment="true" eOpposite="//BehavioralElement/behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehavioralElement" abstract="true" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="//Behavior" eOpposite="//Behavior/behaviouralElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Realtimestatechart" eSuperTypes="//Behavior //NamedElement">
    <eOperations name="main">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="initialize">
      <eAnnotations source="aspect"/>
      <eParameters name="args" upperBound="-1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="step">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="sequentialStep">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1" eType="//Transition" containment="true" eOpposite="//Transition/statechart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1" eType="//State" containment="true" eOpposite="//State/owningRTSC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1" eType="//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1" eType="//Variable" containment="true" eOpposite="//Variable/statechart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clocks" upperBound="-1" eType="//Clock" containment="true" eOpposite="//Clock/statechart"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rounds" unique="false">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="//Vertex //NamedElement">
    <eOperations name="entry">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="exit">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subStatecharts" upperBound="-1" eType="//Realtimestatechart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningRTSC" lowerBound="1" eType="//Realtimestatechart" eOpposite="//Realtimestatechart/states"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransitions" upperBound="-1" eType="//Transition" eOpposite="//Transition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" upperBound="-1" eType="//Transition" eOpposite="//Transition/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="//NamedElement">
    <eOperations name="canFire">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="fire" eType="//Vertex">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="guardsHold">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="clocksHold">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="checkMessages">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="consumeMessages">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//State" eOpposite="//State/outgoingTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//State" eOpposite="//State/incomingTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guards" upperBound="-1" eType="//Guard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clockConstraints" upperBound="-1" eType="//ClockConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" lowerBound="1" eType="//Realtimestatechart" eOpposite="//Realtimestatechart/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggerMessage" upperBound="-1" eType="//MessageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hitCount" unique="false">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" unique="false">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard">
    <eOperations name="evaluate">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" defaultValueLiteral="">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClockConstraint">
    <eOperations name="evaluate">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="checkFederation" eType="//Federation"/>
    </eOperations>
    <eOperations name="apply">
      <eAnnotations source="aspect"/>
      <eParameters name="federation" eType="//Federation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clock" lowerBound="1" eType="//Clock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" lowerBound="1" defaultValueLiteral="0">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" eType="//Realtimestatechart" eOpposite="//Realtimestatechart/variables"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtimeValue" unique="false">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clock" eSuperTypes="//NamedElement">
    <eOperations name="initialize">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="printValue">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" lowerBound="1" eType="//Realtimestatechart" eOpposite="//Realtimestatechart/clocks"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uClock" unique="false" eType="//UDBMClock">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="//BehavioralElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviour" eType="//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingBuffer" eType="//MessageBuffer" containment="true" eOpposite="//MessageBuffer/port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageBuffer">
    <eOperations name="getMessage" eType="//Message">
      <eAnnotations source="aspect"/>
      <eParameters name="type" eType="//MessageType"/>
    </eOperations>
    <eOperations name="hasMessage">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="type" eType="//MessageType"/>
    </eOperations>
    <eOperations name="addMessage">
      <eAnnotations source="aspect"/>
      <eParameters name="message" eType="//Message"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="//Port" eOpposite="//Port/incomingBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1" upperBound="-1" eType="//MessageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allMessages" unique="false" upperBound="-1" eType="//Message">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoints" lowerBound="2" upperBound="2" eType="//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinationProtocol" eSuperTypes="//NamedElement">
    <eOperations name="main">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="initialize">
      <eAnnotations source="aspect"/>
      <eParameters name="arguments" upperBound="-1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="2" upperBound="2" eType="//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" lowerBound="1" eType="//Connector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageType" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//MessageType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statecharts" upperBound="-1" eType="//Realtimestatechart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" upperBound="-1" eType="//CoordinationProtocol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageTypeRepo" lowerBound="1" eType="//MessageTypeRepository" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageTypeRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageTypes" upperBound="-1" eType="//MessageType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Federation" instanceClassName="org.muml.udbm.Federation">
    <eAnnotations source="aspect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="UDBMClock" instanceClassName="org.muml.udbm.UDBMClock">
    <eAnnotations source="aspect"/>
  </eClassifiers>
</ecore:EPackage>
